version: "3"
services:
  app:
    container_name: express
    restart: always
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
    - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - ./data:/data/db